title: KD9A
description: KD9A
url: http://lukascrockett.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-feed
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github:
   twitter:
   facebook:
   email: lukas.crockett@gmail.com

#google_analytics: "UA-85359881-1"
